% v is unit vector
% a is angle in rad

function r = get_rotation(u, a)

    r = [...
        cos(a)+u(1)^2*(1-cos(a)),...
        u(1)*u(2)*(1-cos(a))-u(3)*sin(a),...
        u(1)*u(3)*(1-cos(a))+u(2)*sin(a);...
        
        u(2)*u(1)*(1-cos(a))+u(3)*sin(a),...
        cos(a)+u(2)^2*(1-cos(a)),...
        u(2)*u(3)*(1-cos(a))-u(3)*sin(a);...
        
        u(3)*u(1)*(1-cos(a))-u(2)*sin(a),...
        u(3)*u(2)*(1-cos(a))+u(1)*sin(a),...
        cos(a)+u(3)^2*(1-cos(a))...
        ];

end
